
version: "3.4"

services:

  db:
    image: mariadb:10.5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - bridge-network
    restart: always
  
  migration:
    image: flyway/flyway:7
    command: -url=jdbc:mariadb://db:3306/${DATABASE} -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=120 migrate
    volumes:
      - ./db/migration:/flyway/sql
    networks:
      - bridge-network
    depends_on:
      - db

networks:
  bridge-network:
    driver: bridge

volumes:
  mariadb-data-volume:
